name: my_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_android_lifecycle: 2.0.18
  sqflite: ^2.3.2
  flutter_mobx: ^2.2.0+2
  mobx: ^2.3.0+1
  dio: ^5.4.1
  get_it: ^7.6.7
  material_design_icons_flutter: ^7.0.7296
  jwt_decode: ^0.3.1
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  rflutter_alert: ^2.0.7
  oktoast: ^3.4.0
  icons_launcher: ^2.1.7
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.0.2
  image_picker: ^1.0.7
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.0+1  
  build_runner: ^2.4.8

icons_launcher:
  image_path: "assets/icons/favicon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/logo_inicial.png
    - assets/icons/favicon.png
    